export const CATEGORIES = [
  { name: 'Plomero', slug: 'plomero', icon: '🔧', description: 'Instalación y reparación de tuberías, fugas y sanitarios' },
  { name: 'Electricista', slug: 'electricista', icon: '⚡', description: 'Instalaciones eléctricas, cableado y reparaciones' },
  { name: 'Albañil', slug: 'albanil', icon: '🧱', description: 'Construcción, remodelación y obra civil' },
  { name: 'Mecánico', slug: 'mecanico', icon: '🔩', description: 'Reparación y mantenimiento de vehículos' },
  { name: 'Jardinero', slug: 'jardinero', icon: '🌿', description: 'Diseño, mantenimiento y poda de jardines' },
  { name: 'Carpintero', slug: 'carpintero', icon: '🪚', description: 'Muebles, puertas, ventanas y trabajos en madera' },
  { name: 'Pintor', slug: 'pintor', icon: '🖌️', description: 'Pintura interior, exterior y acabados decorativos' },
  { name: 'Cerrajero', slug: 'cerrajero', icon: '🔑', description: 'Apertura, cambio y reparación de cerraduras' },
  { name: 'Técnico en electrodomésticos', slug: 'tecnico-electrodomesticos', icon: '🔌', description: 'Reparación de lavadoras, refrigeradores y más' },
  { name: 'Limpieza del hogar', slug: 'limpieza-hogar', icon: '🧹', description: 'Limpieza general, profunda y mantenimiento del hogar' },
  { name: 'Veterinario', slug: 'veterinario', icon: '🐾', description: 'Atención médica y cuidado de mascotas' },
  { name: 'Músico', slug: 'musico', icon: '🎵', description: 'Clases de música, bandas y eventos' },
  { name: 'Médico', slug: 'medico', icon: '🩺', description: 'Consultas médicas generales a domicilio' },
  { name: 'Asesor Académico', slug: 'asesor-academico', icon: '📚', description: 'Tutorías, clases particulares y apoyo escolar' },
  { name: 'Fotógrafo', slug: 'fotografo', icon: '📸', description: 'Fotografía de eventos, retratos y comercial' },
  { name: 'Manualidades', slug: 'manualidades', icon: '🎨', description: 'Artesanías, decoración y trabajos a mano' },
  { name: 'Repartidor', slug: 'repartidor', icon: '🛵', description: 'Entregas y mensajería local en Tepeji del Río' },
  { name: 'Mesero', slug: 'mesero', icon: '🍽️', description: 'Servicio de meseros para eventos y celebraciones' },
  { name: 'Tatuador', slug: 'tatuador', icon: '🪡', description: 'Tatuajes y arte corporal profesional' },
  { name: 'Abogado', slug: 'abogado', icon: '⚖️', description: 'Asesoría y servicios legales' },
  { name: 'Belleza y Bienestar', slug: 'belleza-bienestar', icon: '💅', description: 'Estética, maquillaje, masajes y cuidado personal' },
]
